# Generated by Django 3.2.7 on 2023-06-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(default='EN', max_length=20),
        ),
    ]
