# Generated by Django 3.2.7 on 2023-06-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_gift_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default='4.00', max_digits=99999999999999),
        ),
        migrations.AddField(
            model_name='product',
            name='headline',
            field=models.TextField(blank=True, default='here is a headline', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='instructional_level',
            field=models.CharField(default='All levels', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='gift_url',
            field=models.CharField(default='https://www.udemy.com/', max_length=2000),
        ),
    ]
